### PR TITLE
Add a CHANGELOG

### PR DESCRIPTION
**Pull request by DJMcNab**
Based on linebender/vello#604

### CODE REVIEW

**Review by waywardmonkeys — COMMENTED** [review]
I'd been thinking about doing this ... but one thing that held me back (other than time) is that I thought that `parley` and `fontique` should have separate change logs.

**Comment by DJMcNab** [comment]
I think we're planning on doing combined releases for these crates, which suggests a combined changelog makes sense.
But I'm no expert

**Comment by waywardmonkeys** [comment]
I thought part of the appeal of splitting them was that people would be able to use fontique by itself...

**Comment by DJMcNab** [comment]
Sure? But the release strategy of doing the releases at the same time.

Consider [wgpu](https://github.com/gfx-rs/wgpu) for example. They release naga and wgpu at the same time, but projects (such as our `vello_shaders`) can use naga without using wgpu.

**Review by nicoburns — APPROVED** [review]

**Pull request merged**
