### PR TITLE
tiny_skia_render: Fix unused qualifications.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Review by nicoburns — APPROVED** [review]

**Comment by xStrom** [comment]
This is a bit of a head scratcher.

The merge queue CI did

```sh
git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +94c5d78214b0a2c50d0c3e11d700a0e38080e7b9:refs/remotes/origin/gh-readonly-queue/main/pr-55-c982ffc22e861f66419b43b7323fea3754085c6d
```

which seems to correctly already have this lint. However it didn't trigger during the clippy run. 😕

**Comment by waywardmonkeys** [comment]
This happened in my multi-crate PR because that leaves `examples` at the top level so they're now more correctly compiled independently, I think. But now I'm having other CI troubles in that PR.

**Comment by xStrom** [comment]
Well the thing is that the following fails locally for me:

```sh
git checkout 94c5d78214b0a2c50d0c3e11d700a0e38080e7b9
cargo hack clippy -p tiny_skia_render --locked --optional-deps --each-feature
```

Which is what the merge queue CI allegedly did.

**Comment by waywardmonkeys** [comment]
Well, on a related topic maybe, I was getting a warning about the unused `StyleData` when building locally since before the release, yet it apparently never failed in CI.

**Comment by nicoburns** [comment]
Yeah, I had a bunch of issues with CI checks not matching local checks with my PRs. I'm not entirely convinced by "cargo hack", although manually writing out feature combinations isn't great either.

**Comment by xStrom** [comment]
Manually maintaining the package + feature matrix is untenable. Cargo hack has served us well. I have found some issues, but its maintainer is very responsive and accepted my patches. So if you find any issues with cargo hack, definitely let me know.

As for this issue right here, it has nothing to do with cargo hack.

Turns out that this `unused_qualifications` lint requires 1.78 and the Parley CI is still configured to run 1.77. So no weirdness, just a tiny bit stale config.

**Pull request merged**
